name: Atualizar Contador de Dias

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do CÃ³digo
        uses: actions/checkout@v2

      - name: Atualizar Contador
        run: |
          start_date="2023-09-13"
          current_date=$(date -u "+%Y-%m-%d")
          days=$(( ( $(date -ud "$current_date" +%s) - $(date -ud "$start_date" +%s) ) / 86400 ))

          echo "$days" > counter.txt

      - name: Commit e Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add counter.txt
          git commit -m "Atualizar contador de dias"
          git push
